import * as vscode from 'vscode';
import * as path from 'path';
import { IgnoreGroup } from '../detector/technologyDetector';
import { DuplicateCleaner } from './duplicateCleaner';
import { FileUtils } from '../utils/fileUtils';
import { Logger } from '../utils/logger';
import { GITIGNORE_FILE } from '../utils/constants';

export interface UpdateResult {
  addedRules: number;
  skippedRules: number;
  content: string;
  isNew: boolean;
}

export class GitignoreUpdater {
  private cleaner = new DuplicateCleaner();

  async update(
    workspaceRoot: string,
    groups: IgnoreGroup[]
  ): Promise<UpdateResult> {
    const gitignorePath = path.join(workspaceRoot, GITIGNORE_FILE);
    const exists = await FileUtils.exists(gitignorePath);
    let existingContent = '';

    if (exists) {
      existingContent = await FileUtils.readFile(gitignorePath);
      Logger.info('Existing .gitignore found, merging rules');
    } else {
      Logger.info('No .gitignore found, creating new one');
    }

    const existingRules = this.cleaner.extractExistingRules(existingContent);
    const config = vscode.workspace.getConfiguration('smartGitIgnore');
    const shouldGroup = config.get<boolean>('groupRules', true);
    const shouldSort = config.get<boolean>('sortRules', true);

    let addedRules = 0;
    let skippedRules = 0;
    const newSections: string[] = [];

    for (const group of groups) {
      const missingRules = group.rules.filter(r => !existingRules.has(r));

      if (missingRules.length === 0) {
        skippedRules += group.rules.length;
        continue;
      }

      skippedRules += group.rules.length - missingRules.length;
      addedRules += missingRules.length;

      const sortedRules = shouldSort
        ? [...missingRules].sort((a, b) => a.localeCompare(b))
        : missingRules;

      if (shouldGroup) {
        newSections.push(group.comment);
        newSections.push(...sortedRules);
        newSections.push('');
      } else {
        newSections.push(...sortedRules);
      }
    }

    let finalContent = existingContent;

    if (newSections.length > 0) {
      const separator = existingContent.endsWith('\n') ? '' : '\n';
      finalContent = existingContent + separator + newSections.join('\n');
    }

    // Final dedup pass
    const { cleaned } = this.cleaner.clean(finalContent);
    finalContent = cleaned;

    return {
      addedRules,
      skippedRules,
      content: finalContent,
      isNew: !exists,
    };
  }

  async write(workspaceRoot: string, content: string): Promise<void> {
    const gitignorePath = path.join(workspaceRoot, GITIGNORE_FILE);
    await FileUtils.writeFile(gitignorePath, content);
    Logger.info(`Written .gitignore to ${gitignorePath}`);
  }

  async generate(workspaceRoot: string, groups: IgnoreGroup[]): Promise<UpdateResult> {
    const config = vscode.workspace.getConfiguration('smartGitIgnore');
    const shouldGroup = config.get<boolean>('groupRules', true);
    const shouldSort = config.get<boolean>('sortRules', true);

    const lines: string[] = [
      '# Generated by Smart GitIgnore',
      '# https://marketplace.visualstudio.com/items?itemName=smart-gitignore',
      '',
    ];

    let totalRules = 0;

    for (const group of groups) {
      if (group.rules.length === 0) {
        continue;
      }

      const sortedRules = shouldSort
        ? [...group.rules].sort((a, b) => a.localeCompare(b))
        : group.rules;

      if (shouldGroup) {
        lines.push(group.comment);
      }
      lines.push(...sortedRules);
      lines.push('');
      totalRules += sortedRules.length;
    }

    const content = lines.join('\n');

    return {
      addedRules: totalRules,
      skippedRules: 0,
      content,
      isNew: true,
    };
  }
}
