import { IgnoreGroup } from '../detector/technologyDetector';
import { CATEGORIES } from '../utils/constants';

export function getPythonRules(): IgnoreGroup[] {
  return [
    {
      category: CATEGORIES.PYTHON,
      comment: '# Python',
      rules: [
        '__pycache__/',
        '*.py[cod]',
        '*$py.class',
        '*.so',
        '.Python',
        'build/',
        'develop-eggs/',
        'dist/',
        'downloads/',
        'eggs/',
        '.eggs/',
        'lib/',
        'lib64/',
        'parts/',
        'sdist/',
        'var/',
        'wheels/',
        '*.egg-info/',
        '.installed.cfg',
        '*.egg',
        'MANIFEST',
        'pip-log.txt',
        'pip-delete-this-directory.txt',
        '.tox/',
        '.nox/',
        '.coverage',
        '.coverage.*',
        '.cache',
        '.pytest_cache/',
        'htmlcov/',
        '*.cover',
        '.hypothesis/',
        '.mypy_cache/',
        '.dmypy.json',
        'dmypy.json',
        'venv/',
        '.venv/',
        'env/',
        '.env/',
        'ENV/',
        'env.bak/',
        'venv.bak/',
        '.spyderproject.db',
        '.spyproject',
        '.ropeproject',
        '/site',
        '.pdm.toml',
        '__pypackages__/',
        'celerybeat-schedule',
        'celerybeat.pid',
        '*.sage.py',
        '.ipynb_checkpoints',
        'profile_default/',
        'ipython_config.py',
        'Pipfile.lock',
      ],
    },
  ];
}
