import * as vscode from 'vscode';
import { GitignoreUpdater } from '../../updater/gitignoreUpdater';
import { IgnoreGroup } from '../../detector/technologyDetector';
import { CATEGORIES } from '../../utils/constants';

// Helpers
function makeGroup(comment: string, rules: string[], category = CATEGORIES.NODE): IgnoreGroup {
  return { comment, rules, category };
}

function mockNoGitignore() {
  // stat throws → file does not exist
  (vscode.workspace.fs.stat as jest.Mock).mockRejectedValue(new Error('not found'));
}

function mockExistingGitignore(content: string) {
  (vscode.workspace.fs.stat as jest.Mock).mockResolvedValue({ size: content.length });
  const bytes = Buffer.from(content, 'utf-8');
  (vscode.workspace.fs.readFile as jest.Mock).mockResolvedValue(bytes);
}

function mockConfig(overrides: Record<string, unknown> = {}) {
  (vscode.workspace.getConfiguration as jest.Mock).mockReturnValue({
    get: (key: string, def: unknown) => (key in overrides ? overrides[key] : def),
  });
}

const ROOT = '/workspace';

beforeEach(() => {
  jest.clearAllMocks();
  mockConfig({ groupRules: true, sortRules: true });
});

describe('GitignoreUpdater', () => {
  let updater: GitignoreUpdater;

  beforeEach(() => {
    updater = new GitignoreUpdater();
  });

  // ─── generate() ──────────────────────────────────────────────────────────

  describe('generate()', () => {
    it('generates content with header comment', async () => {
      const groups = [makeGroup('# Node', ['node_modules/', 'dist/'])];
      const result = await updater.generate(ROOT, groups);
      expect(result.content).toContain('# Generated by Smart GitIgnore');
    });

    it('counts all rules as added', async () => {
      const groups = [makeGroup('# Node', ['node_modules/', 'dist/'])];
      const result = await updater.generate(ROOT, groups);
      expect(result.addedRules).toBe(2);
      expect(result.skippedRules).toBe(0);
      expect(result.isNew).toBe(true);
    });

    it('includes section comment when groupRules=true', async () => {
      const groups = [makeGroup('# Node', ['node_modules/'])];
      const result = await updater.generate(ROOT, groups);
      expect(result.content).toContain('# Node');
    });

    it('omits section comment when groupRules=false', async () => {
      mockConfig({ groupRules: false, sortRules: false });
      const groups = [makeGroup('# Node', ['node_modules/'])];
      const result = await updater.generate(ROOT, groups);
      expect(result.content).not.toContain('# Node');
    });

    it('sorts rules alphabetically when sortRules=true', async () => {
      const groups = [makeGroup('# Node', ['z-last/', 'a-first/', 'm-middle/'])];
      const result = await updater.generate(ROOT, groups);
      const idx = (s: string) => result.content.indexOf(s);
      expect(idx('a-first/')).toBeLessThan(idx('m-middle/'));
      expect(idx('m-middle/')).toBeLessThan(idx('z-last/'));
    });

    it('does not sort when sortRules=false', async () => {
      mockConfig({ groupRules: false, sortRules: false });
      const groups = [makeGroup('# Node', ['z-last/', 'a-first/'])];
      const result = await updater.generate(ROOT, groups);
      expect(result.content.indexOf('z-last/')).toBeLessThan(result.content.indexOf('a-first/'));
    });

    it('handles empty groups array', async () => {
      const result = await updater.generate(ROOT, []);
      expect(result.addedRules).toBe(0);
      expect(result.content).toContain('# Generated by Smart GitIgnore');
    });
  });

  // ─── update() ────────────────────────────────────────────────────────────

  describe('update()', () => {
    it('creates new file when .gitignore does not exist', async () => {
      mockNoGitignore();
      const groups = [makeGroup('# Node', ['node_modules/'])];
      const result = await updater.update(ROOT, groups);
      expect(result.isNew).toBe(true);
      expect(result.addedRules).toBe(1);
    });

    it('skips rules already in existing .gitignore', async () => {
      mockExistingGitignore('node_modules/\ndist/\n');
      const groups = [makeGroup('# Node', ['node_modules/', 'dist/', 'build/'])];
      const result = await updater.update(ROOT, groups);
      expect(result.skippedRules).toBe(2);
      expect(result.addedRules).toBe(1);
    });

    it('appends only missing rules', async () => {
      mockExistingGitignore('node_modules/\n');
      const groups = [makeGroup('# Node', ['node_modules/', 'dist/'])];
      const result = await updater.update(ROOT, groups);
      expect(result.content).toContain('dist/');
      expect(result.content).toContain('node_modules/');
    });

    it('preserves existing custom rules', async () => {
      const existing = '# My custom rule\nmy-secret.json\nnode_modules/\n';
      mockExistingGitignore(existing);
      const groups = [makeGroup('# Node', ['node_modules/', 'dist/'])];
      const result = await updater.update(ROOT, groups);
      expect(result.content).toContain('my-secret.json');
      expect(result.content).toContain('# My custom rule');
    });

    it('preserves existing comments', async () => {
      mockExistingGitignore('# Existing comment\nnode_modules/\n');
      const groups = [makeGroup('# Node', ['dist/'])];
      const result = await updater.update(ROOT, groups);
      expect(result.content).toContain('# Existing comment');
    });

    it('returns 0 added rules when all rules already present', async () => {
      mockExistingGitignore('node_modules/\ndist/\n');
      const groups = [makeGroup('# Node', ['node_modules/', 'dist/'])];
      const result = await updater.update(ROOT, groups);
      expect(result.addedRules).toBe(0);
    });

    it('does not duplicate rules in final output', async () => {
      mockExistingGitignore('node_modules/\n');
      const groups = [makeGroup('# Node', ['node_modules/', 'dist/'])];
      const result = await updater.update(ROOT, groups);
      const count = result.content.split('\n').filter(l => l.trim() === 'node_modules/').length;
      expect(count).toBe(1);
    });

    it('sets isNew=false when file already exists', async () => {
      mockExistingGitignore('node_modules/\n');
      const groups = [makeGroup('# Node', ['dist/'])];
      const result = await updater.update(ROOT, groups);
      expect(result.isNew).toBe(false);
    });
  });

  // ─── write() ────────────────────────────────────────────────────────────

  describe('write()', () => {
    it('calls vscode.workspace.fs.writeFile with correct URI', async () => {
      (vscode.workspace.fs.writeFile as jest.Mock).mockResolvedValue(undefined);
      await updater.write(ROOT, 'node_modules/\n');
      expect(vscode.workspace.fs.writeFile).toHaveBeenCalledTimes(1);
    });

    it('writes UTF-8 encoded content', async () => {
      (vscode.workspace.fs.writeFile as jest.Mock).mockResolvedValue(undefined);
      const content = 'node_modules/\ndist/\n';
      await updater.write(ROOT, content);
      const [, written] = (vscode.workspace.fs.writeFile as jest.Mock).mock.calls[0];
      expect(Buffer.from(written).toString('utf-8')).toBe(content);
    });
  });
});
